name: Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic Version'
        required: true
      dry-run:
        description: 'Dry run (no push, no release, no deploy)'
        type: boolean
        default: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: '25'
          distribution: 'corretto'

      - name: Set release version
        run: |
          sed -i "s/^version=.*/version=${{ github.event.inputs.version }}/" gradle.properties

      - name: Commit release version
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Set release version to ${{ github.event.inputs.version }}"

      - name: Push
        if: ${{ !inputs.dry-run }}
        run: git push

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      # Build the artifacts
      - name: Build & Stage
        run: ./gradlew build :lib:publish

      # Create a release
      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        with:
          arguments: 'full-release'
        env:
          JRELEASER_DRY_RUN: ${{ inputs.dry-run }}
          JRELEASER_PROJECT_VERSION: ${{ inputs.version }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}

      # Persist logs
      - name: JReleaser release output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties